{% set name = "quantulum3" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9e2cf465fed7242d7069ae601ba50c367c9ceac510d0c3414dda2173645bbf09

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - inflect
    - num2words

test:
  imports:
    - quantulum3
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/nielstron/quantulum3
  summary: Library for unit extraction under active development - fork of quantulum
  description: |
    Python library for information extraction of quantities, measurements and
    their units from unstructured text. It is able to disambiguate between
    similar looking units based on their k-nearest neighbours in their
    [GloVe](https://nlp.stanford.edu/projects/glove/) vector representation.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/nielstron/quantulum3
  dev_url: https://github.com/nielstron/quantulum3

extra:
  recipe-maintainers:
    - kynan
