{% set name = "quantulum3" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 797b5d94c52d23107010838fbf2d3bb4f15630f4e90556401bdb042a1c12fc1e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - inflect
    - num2words

test:
  imports:
    - quantulum3
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/nielstron/quantulum3
  summary: Library for unit extraction under active development - fork of quantulum
  description: |
    Python library for information extraction of quantities, measurements and
    their units from unstructured text. It is able to disambiguate between
    similar looking units based on their k-nearest neighbours in their
    [GloVe](https://nlp.stanford.edu/projects/glove/) vector representation.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/nielstron/quantulum3
  dev_url: https://github.com/nielstron/quantulum3

extra:
  recipe-maintainers:
    - kynan
